In [3]:
import numpy as np

In [25]:
a = np.array([[2, -1, 3],
    [-4, -3, -2],
    [3, 1, -1]], dtype=float)

b = np.array([5, 8, 4])
 
x = np.zeros_like(b)

if a[0, 0] != 1:
    b[0] /= a[0, 0]
    a[0, :] /= a[0, 0]

b[1] -= a[1, 0] * b[0]
a[1, :] -= a[1, 0] * a[0, :]
b[2] -= a[2, 0] * b[0]
a[2, :] -= a[2, 0] * a[0, :]


if a[1, 0] != 1:
    b[1] /= a[1, 1]
    a[1, :] /= a[1, 1]

b[2] -= a[2, 1] * b[1]
a[2, :] -= a[2, 1] * a[1, :]

x[2] = b[2] / a[2, 2]
x[1] = (b[1] - x[2] * a[1, 2]) / a[1, 1]
x[0] = (b[0] - x[1] * a[0, 1] - x[2] * a[0, 2]) / a[0, 0]

print(f"{x}\n{a}\n{b}")



[ 2 -3 -1]
[[ 1.  -0.5  1.5]
 [-0.   1.  -0.8]
 [ 0.   0.  -3.5]]
[ 2 -3  5]
